title: Islamic Endowment Advisors
description: >
  The Islamic Endowment Foundation helps establish, grow, and advise
  endowment funds for mosques and Islamic organizations across the United States.
baseurl: ""
url: ""

org:
  name: Islamic Endowment Advisors
  tagline: Serving the Institutions That Serve Everyone
  email: info@islamicendowmentadvisors.org
  location: United States

plugins:
  - jekyll-feed
